### ISSUE TITLE
Không thể cập nhật video lên nv4.0.29

### ISSUE THREAD

**Issue by hoanglongvnpt** [hoaquynhtim99/video-clip-update#1]
làm theo hướng dẫn tại đây: https://github.com/hoaquynhtim99/video-clip-update/tree/4.0.29
![3](https://cloud.githubusercontent.com/assets/11238423/15526429/2be189e4-225c-11e6-8fd9-3751028f586d.png)
Và tiến hành nâng cấp thì nhận được thông báo
![4](https://cloud.githubusercontent.com/assets/11238423/15526437/3f42dd76-225c-11e6-8efa-e8436fd1cad8.png)
Mong được pix lỗi. Thanh hoaquynhtim99

**Comment by hoaquynhtim99** [comment]
Cái này bạn đã cài module video mới nhất rồi mà cần gì nâng cấp nữa nhỉ
